# Conda Environment Setup Instructions ----
#  - Using an environment.yml file with conda
#  - Key Terminal Commands:
#
#    conda env create -f src/env-setup/conda_env_setup.yml
#    conda env update --file src/env-setup/conda_env_setup.yml --prune
#    conda env export --name modern_tsf > envname.yml
#    conda env remove --name modern_tsf
#    conda env list
#    conda source activate modern_tsf
#    pip freeze > ./src/env-setup/requirements.txt

name: modern_tsf
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.11.9
  - pip 
  - pip:

      # Core Data
      - numpy >= 2.0.0, < 3.0.0
      - pandas >= 2.2.0, < 3.0.0
      - pyarrow
      - polars >= 1.6.0, < 2.0.0

      # Visualization
      - matplotlib >= 3.7.0, < 4.0.0
      - plotly >= 6.0.0, < 7.0.0

      # Statistics
      - scipy >= 1.15.0, < 2.0.0

      # Time Series
      - statsmodels < 1.0.0
      - pytimetk >= 2.0.0, < 3.0.0
      # - prophet >= 1.1.0, < 2.0.0
      
      # Machine Learning
      - scikit-learn >= 1.5.0, < 2.0.0
      # - xgboost >= 2.1.0, < 3.0.0
      # - lightgbm >= 4.5.0, < 5.0.0
      # - catboost >= 1.2.0, < 2.0.0

      # H2O - AutoML
      # - h2o

      # Optimization
      # - hyperopt >= 0.2.0, < 1.0.0
      # - ray >= 2.30.0, < 3.0.0
      # - optuna >= 4.0.0, < 5.0.0

      # Nixtla-verse
      - datasetsforecast
      - coreforecast
      - utilsforecast
      - statsforecast >= 2.0.0, < 3.0.0
      - mlforecast >= 1.0.0, < 2.0.0
      - neuralforecast >= 3.0.0, < 4.0.0
      - hierarchicalforecast >= 1.0.0, < 2.0.0
      - nixtla


